# Generated by Django 4.2.5 on 2023-09-25 00:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Applications",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("App_name", models.CharField(max_length=16, verbose_name="app_name")),
                (
                    "App_intro",
                    models.CharField(max_length=256, verbose_name="app_intro"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Departments",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Dep_name", models.CharField(max_length=16, verbose_name="dep_name")),
                (
                    "Dep_intro",
                    models.CharField(max_length=256, verbose_name="dep_intro"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Roles",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "Role_name",
                    models.CharField(max_length=16, verbose_name="role_name"),
                ),
                (
                    "Role_intro",
                    models.CharField(max_length=256, verbose_name="role_intro"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employees",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Emp_name", models.CharField(max_length=32)),
                (
                    "Emp_dep",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="employee.departments",
                    ),
                ),
                ("Emp_res_apps", models.ManyToManyField(to="employee.applications")),
                (
                    "Emp_role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="employee.roles"
                    ),
                ),
            ],
        ),
    ]
