# Generated by Django 3.1.5 on 2023-09-24 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Emp_name', models.CharField(max_length=32)),
                ('Emp_dep', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.departments')),
                ('Emp_res_apps', models.ManyToManyField(to='employee.Applications')),
                ('Emp_role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.roles')),
            ],
        ),
    ]
