# Generated by Django 4.2.5 on 2023-09-25 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="roles",
            name="Role_name",
            field=models.CharField(max_length=56, verbose_name="role_name"),
        ),
    ]
