# Generated by Django 4.2.5 on 2023-09-25 02:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("employee", "0002_alter_roles_role_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employees",
            name="Emp_dep",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.departments",
                verbose_name="emp_dep",
            ),
        ),
        migrations.AlterField(
            model_name="employees",
            name="Emp_name",
            field=models.CharField(max_length=32, verbose_name="emp_name"),
        ),
        migrations.AlterField(
            model_name="employees",
            name="Emp_role",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="employee.roles",
                verbose_name="emp_role",
            ),
        ),
    ]
